categories:
  Food:
    "[Food and groceries]":
      - ica nära
      - willys
      - coop
      - rusta backaplan
      - ica supermarket
      - Gott i Gott
      - HELLOFRESH
      - ICA KVANTUM
      - GOTEBORGS ORIEN
      - GLADE JOHANS
      - LIDL
      - eleven
      - CO 252 BACKAPLA
      - Hemköp
      - Saigon city
      - Indian groc
      - GARDSSALLSKAPET
      - INDIAN SUPERMARKET
      - Ica nara
      - Ica super
      - KONDITORI
      - Asian Liv
      - MINI STOP ASIAN FOOD
      - HISINGENS FISK
      - ARJEPLOGVILT

  Base:
    Pharmacy:
      - Apotek
      - apohem
      - Apotea
      - W*meds.com

    Dental:
      - frisktandv
      - AQUA DENTAL
      - Hisingen Tandvard
      - LINNEGATANS IMPLANTATK

    "[Hair cutting]":
      - Live Salong
      - Barbersh

    Makeup:
      - Kicks

    Gym:
      - Nordicwell

    "[Protein & supplements]":
      - GYMGROSSISTEN
    CSN:
      - csn
    Akassa:
      - Akad.a-kassa
    Bank:
      - enkla vardag
      - ÅRSAVGIFT
    Phone:
      - hallon.se
      - hallon

  Home:
    Electricity:
      - gbg energi
      - göteborg energi
      - dinel

  Transport:
    "[Public Transportation]":
      - VASTTRAFIK
      - Västtrafik
    "[Parking home]":
      - Cyklisten parkerings
    "Parking":
      - Easypark
      - PARKSTER
    Gasoline:
      - OKQ8
      - INGO
      - ST1
    Fordonsskatt:
      - Fordonsskatt
    "[Car wash]":
      - GRIMBOS MEK
    "[Congestion tax]":
      - Trängselskat
    "[Infrastructure fee]":
      - Infrastrukt
  Fun:
    "[Computer games]":
      - STEAMGAMES
    Cinema:
      - FILMSTADEN
    Streaming:
      - spotify
      - netflix.com
      - hbomax
      - audible
      - GOOGLE STORAGE
      - discovery+
    Alcohol:
      - systembolaget
      - SCHNITZELPLATZ
      - ZAMENHOF
      - IRISH EMBASSY JERNTORG
      - Systembolage

    Cafe:
      - Asti Italia
      - BROGYLLEN LANDALA
      - ESPRESSO HOUSE
      - Pressbyran
      - Hastevikskiosk
      - Jafaris Group

    "[Eating out]":
      - lilla istanbul
      - zosaki
      - sannegardens
      - restaurang istanbul
      - sushi tiden
      - DA BELLO ENOTECA
      - FOOD LAB
      - Kafe Alkemiste
      - INDISKA
      - COOP KONSUM
      - ZOZAKI JAPAN
      - BURGER KING
      - SUBWAY
      - FLYING BARELL
      - MEXIKANSKA MONARKIN
      - OLSTUGAN TULLEN
      - LILLA ISTANBUL
      - NADIAS RESTAURANG
      - Ramen-ya
      - Streetfood f
      - MOON THAI KITCHEN
      - Dubbel Gard
      - SYLOS
      - Lacsa pizzer
      - BACKAPLAN WOK
      - KG KELLARE
      - Osman s Grill
      - Morgon Coffee Roas
      - RESTAURANG CITY
      - MAX SKELLEFTEA
      - BAGERIET VEMDALEN
      - RESTAURANG TRIPTI
      - IDREGRILLEN
      - MCDONALDS
      - GLOBAL RESTAURANG
      - RESTAURANG MARIA
      - LUCKY SUSHI
      - INDIAN PALACE
      - FRASSES ARJEPLO
      - PIZZERIA
      - KANJANA BRANNSTROM THA
      - Cheers Pub
      - Foodora
      - JARNGRILLEN
      - SPIKAT
      - GOLDEN WAFFEL

  Spending:
    Hornbach:
      - HORNBACH
    Zalando:
      - Zalando
    Stadium:
      - STADIUM
    Ahlens:
      - AHLENS
    Netonnet:
      - Netonnet
    "[H&M]":
      - HM SE0221
    Kjell:
      - KJELL
    Amazon:
      - AMAZONRETAIL
    "[Book store]":
      - AKADEMIBOKHANDE
    Blomsterlandet:
      - BLOMSTERLANDET
    "[Add Nature]":
      - addnature
    Airbnb:
      - AIRBNB
    XXL:
      - XXL
    STF:
      - STF RITSEM
    IKEA:
      - IKEA
    Puzzle:
      - pusselavenyn
    Badminton:
      - MATCHi
    Swimming:
      - LUNDBYBADET
    Elgiganten:
      - Elgiganten
    Police:
      - POLISEN
    Klarna:
      - Klarna bank
    Books:
      - Klarna*bokus.com
    Bluebox:
      - Klarna*bluebox.se
    Biltema:
      - BILTEMA
    Flight:
      - KLM
      - PAL AIR DIGITAL
    Ekokul:
      - Ekokul


ignored:
  - entercard group ab
  - lön
  - inbetalning bankgiro
  - netlens
  - Pension
  - skandia liv
  - 56990473967
  - folksam
  - Kåpan