categories:
  Food:
    "[Food and groceries]":
      - ica nära
      - willys
      - Salukott
      - coop
      - ica supermarket
      - Gott i Gott
      - HELLOFRESH
      - ICA KVANTUM
      - GOTEBORGS ORIEN
      - GLADE JOHANS
      - JANNES FISK
      - LIDL
      - HEMKOP
      - eleven
      - CO 252 BACKAPLA
      - Hemköp
      - Saigon city
      - Indian groc
      - GARDSSALLSKAPET
      - INDIAN SUPERMARKET
      - Ica nara
      - Ica super
      - KONDITORI
      - Asian Liv
      - KROKSLATTS LIVS
      - MINI STOP ASIAN FOOD
      - HISINGENS FISK
      - ARJEPLOGVILT
      - DOLLARSTORE
      - KIWI
      - NOJDS

  Kid:
    Healthcare:
      - Barnmorskegrup
      - SAHLGRENSKA SJUKHUSET

  Base:
    Pharmacy:
      - Apotek
      - apohem
      - Apotea
      - W*meds.com

    Dental:
      - frisktandv
      - AQUA DENTAL
      - Hisingen Tandvard
      - LINNEGATANS IMPLANTATK
      - HISINGEN TANDVÅ

    "[Hair cutting]":
      - Live Salong
      - Barbersh
      - DEELPO AB

    Makeup:
      - Kicks

    Doctor:
      - Barnmorskegruppen
      - NILSSON LÄKAR
      - CAPIO

    Gym:
      - Nordicwell

    "[Protein & supplements]":
      - GYMGROSSISTEN

    "[Contact lenses]":
      - misterspex

    CSN:
      - csn
    Akassa:
      - Akad.a-kassa
    Bank:
      - enkla vardag
      - ÅRSAVGIFT
    Phone:
      - hallon.se
      - hallon

  Home:
    Electricity:
      - gbg energi
      - göteborg energi
      - dinel

  Transport:
    "[Public Transportation]":
      - VASTTRAFIK
      - Västtrafik
    "[Parking home]":
      - Cyklisten parkerings
    "Parking":
      - Easypark
      - PARKSTER
      - PARKERING GÖTEB
      - MobilPark
    Gasoline:
      - OKQ8
      - INGO
      - ST1
      - CIRCLE K
      - Qstar
      - CIRCEL K
    Fordonsskatt:
      - Fordonsskatt
    "[Car wash]":
      - GRIMBOS MEK
    "[Congestion tax]":
      - Trängselskat
    "[Infrastructure fee]":
      - Infrastrukt
    "[Car shop]":
      - HISINGE BIL
  Fun:
    "[Computer games]":
      - STEAMGAMES
      - Greenmangaming
      - Blizzard
    Cinema:
      - FILMSTADEN
    Streaming:
      - spotify
      - netflix.com
      - hbomax
      - audible
      - GOOGLE STORAGE
      - discovery+
      - HBO MAX
      - Google Payment
    Boardgames:
      - SF-Bokhandel
      - SPELEXPERTEN.COM

    Alcohol:
      - systembolaget
      - SCHNITZELPLATZ
      - ZAMENHOF
      - IRISH EMBASSY JERNTORG
      - Systembolage
      - Stena Alcohol

    Cafe:
      - Asti Italia
      - BROGYLLEN LANDALA
      - ESPRESSO HOUSE
      - ESPRESSO H
      - LEJONET OCH BJORNEN
      - CONVINI
      - Beautys ca
      - Pressbyran
      - Hastevikskiosk
      - KAFFELABBET
      - Jafaris Group
      - JoeAndTheJuice
      - ME & TEA
      - MR CAKE
      - Forida s
      - Ranias Donuts
      - RODA STEN CAFE O REST
      - MATCHA HOUSE AB
      - Smoothie Swede

    "[Eating out]":
      - lilla istanbul
      - zosaki
      - sannegardens
      - restaurang istanbul
      - Benne över
      - WANG BY WANG
      - sushi tiden
      - DA BELLO ENOTECA
      - VIETNAMHAKET
      - TURKISK SULTAN
      - Benne Oever
      - FOOD LAB
      - RESTAURANG ASIAN MAT
      - Kafe Alkemiste
      - RASA SAYANG
      - INDISKA
      - COOP KONSUM
      - ZOZAKI JAPAN
      - BURGER KING
      - SUBWAY
      - FLYING BARELL
      - MEXIKANSKA MONARKIN
      - OLSTUGAN TULLEN
      - LILLA ISTANBUL
      - NADIAS RESTAURANG
      - MAI THAI TAKE
      - Ramen-ya
      - Streetfood f
      - MOON THAI KITCHEN
      - Dubbel Gard
      - SYLOS
      - Lacsa pizzer
      - BACKAPLAN WOK
      - KG KELLARE
      - Osman s Grill
      - RESTAURANG MARI
      - Morgon Coffee Roas
      - RESTAURANG CITY
      - MAX SKELLEFTEA
      - BAGERIET VEMDALEN
      - RESTAURANG TRIPTI
      - IDREGRILLEN
      - MCDONALDS
      - GLOBAL RESTAURANG
      - SIAM TAKEAWAY
      - RESTAURANG MARIA
      - LUCKY SUSHI
      - INDIAN PALACE
      - FRASSES ARJEPLO
      - PIZZERIA
      - KANJANA BRANNSTROM THA
      - MASALA KITCHEN
      - Cheers Pub
      - Foodora
      - JARNGRILLEN
      - SPIKAT
      - GOLDEN WAFFEL
      - Duy Tan
      - KFC GOTEBORG
      - RESTAURANG NANKING
      - TAWAN THAI KITCHEN
      - Fiskebaren
      - THAI SAMILA KUNGSTEN
      - Stena Mat
      - RESTAURANG BRS
      - NORDIC SPORTBAR
      - Bombay Bistro
      - Sukki-Ne
      - MAC S KEBAB OCH GATUKO
      - KERSTIN PA
      - FLYING BARREL
      - PANDA FAST
      - CORSICA
      - Max Burgers
      - Stejk Street

  Spending:
    Hornbach:
      - HORNBACH
    Zalando:
      - Zalando
    Stadium:
      - STADIUM
    Ahlens:
      - AHLENS
    Netonnet:
      - Netonnet
    "[H&M]":
      - HM SE0221
      - HM SE0444
      - HM SE0210
    "RUSTA":
      - RUSTA
    "Remitly":
      - REMITLY
    "Bauhause":
      - BAUHAUS
    "[Electric scooters]":
      - TIER
      - Ryde
    "[MÖLNDAL GAL]":
      - MÖLNDAL GAL
    Kjell:
      - KJELL
    Intersport:
      - INTERSPORT
    Theater:
      - LORENSBERGSTEATERN
    Amazon:
      - AMAZONRETAIL
    "[Book store]":
      - AKADEMIBOKHANDE
    Blomsterlandet:
      - BLOMSTERLANDET
    "[Add Nature]":
      - addnature
    Airbnb:
      - AIRBNB
    XXL:
      - XXL
    STF:
      - STF RITSEM
    IKEA:
      - IKEA

    Puzzle:
      - pusselavenyn
    Swimming:
      - LUNDBYBADET
    Elgiganten:
      - Elgiganten
    Police:
      - POLISEN
    Klarna:
      - Klarna bank
    Books:
      - Klarna*bokus.com
    Bluebox:
      - Klarna*bluebox.se
    Biltema:
      - BILTEMA
    Flight:
      - KLM
      - PAL AIR DIGITAL
    Ekokul:
      - Ekokul
    Tickster:
      - TICKSTER
    "[Clas Ohlson]":
      - CLAS OHLSON
    "[Stena Cruise]":
      - Stena Line
    "Smartphoto":
      - smartphoto
    "[ÖoB]":
      - OOB BACKAPLAN
    "Lindex":
      - LINDEX
    "Vanbruun":
      - vanbruun
    "Brothers":
      - Brothers Nordstan
    "[SJ Train]":
      - SJ.SE
    "[Jack & Jones]":
      - K*bestseller
    Liseberg:
      - liseberg
    Bio:
      - BIOPALATSET
    Jula:
      - JULA SVERIGE
    KappAhl:
      - KappAhl
    Byggmax:
      - byggmax
    Bokhandel:
      - adlibris
      - bokus
    Babyworld:
      - babyworld
    Apple:
      - apple.com
    "[Lofoten trip]":
      - Booking.c
      - Radisson BLU
      - LAPONIA
      - TORGHATTEN
      - LOFOTR NÆRINGSD
      - LOFOTR VIKI
      - Brim Holding
      - Pattareeya
      - GADUS HAMNØY
    Museum:
      - SJÖFARTSMUSEET
      - VASAMUSEETS
      - UNIVERSEUM
    Migrationsverket:
      - MIGRATIONSVERKE
    Letsdeal:
      - letsdeal

ignored:
  - entercard group ab
  - lön
  - inbetalning bankgiro
  - Pension
  - skandia liv
  - 56990473967
  - folksam
  - Kåpan