categories:
  Food:
    "[Food and groceries]":
      - ica nära
      - willys
      - coop
      - rusta backaplan
      - ica supermarket
      - HELLOFRESH
      - ICA KVANTUM
      - GOTEBORGS ORIEN
      - GLADE JOHANS
      - LIDL
      - eleven
      - CO 252 BACKAPLA
      - Hemköp
      - Saigon city
      - Indian groc
      - GARDSSALLSKAPET
      - INDIAN SUPERMARKET
      - Ica nara
      - Ica super
      - KONDITORI

  Base:
    Pharmacy:
      - Apotek
      - apohem
      - Apotea

    Dental:
      - frisktandv
      - AQUA DENTAL

    "[Hair cutting]":
      - Live Salong
      - Barbersh

    Makeup:
      - Kicks

    Gym:
      - Nordicwell

    "[Protein & supplements]":
      - GYMGROSSISTEN
    CSN:
      - csn
    Akassa:
      - Akad.a-kassa
    Bank:
      - enkla vardag
      - ÅRSAVGIFT
    Phone:
      - hallon.se

  Home:
    Electricity:
      - gbg energi
      - göteborg energi
      - dinel
    "[Home inscurance]":
      - folksam


  Transport:
    "[Public Transportation]":
      - VASTTRAFIK
      - Västtrafik
    "[Parking home]":
      - Cyklisten parkerings

  Fun:
    "[Computer games]":
      - STEAMGAMES
    Cinema:
      - FILMSTADEN
    Streaming:
      - spotify
      - netflix.com
      - hbomax
      - audible
      - GOOGLE STORAGE
      - discovery+
    Alcohol:
      - systembolaget
      - SCHNITZELPLATZ
      - ZAMENHOF
      - IRISH EMBASSY JERNTORG
      - Systembolage

    Cafe:
      - Asti Italia
      - BROGYLLEN LANDALA
      - ESPRESSO HOUSE

    "[Eating out]":
      - lilla istanbul
      - zosaki
      - sannegardens
      - restaurang istanbul
      - sushi tiden
      - DA BELLO ENOTECA
      - FOOD LAB
      - Kafe Alkemiste
      - INDISKA
      - COOP KONSUM
      - ZOZAKI JAPAN
      - BURGER KING
      - SUBWAY
      - FLYING BARELL
      - MEXIKANSKA MONARKIN
      - OLSTUGAN TULLEN
      - LILLA ISTANBUL
      - NADIAS RESTAURANG
      - Ramen-ya
      - Streetfood f
      - MOON THAI KITCHEN
      - Dubbel Gard
      - SYLOS
      - Lacsa pizzer
      - BACKAPLAN WOK
      - Osman s Grill
      - Morgon Coffee Roas

  Spending:
    Hornbach:
      - HORNBACH
    Zalando:
      - Zalando
    Stadium:
      - STADIUM
    Ahlens:
      - AHLENS
    Netonnet:
      - Netonnet
    "[H&M]":
      - HM SE0221
    Kjell:
      - KJELL
    Amazon:
      - AMAZONRETAIL
    "[Book store]":
      - AKADEMIBOKHANDE
    Blomsterlandet:
      - BLOMSTERLANDET

ignored:
  - entercard group ab
  - lön
  - inbetalning bankgiro
  - netlens
  - Pension
  - skandia liv
  - 56990473967