categories:
  Food:
    "[Food and groceries]":
      - ica nära
      - willys
      - coop
      - rusta backaplan
      - ica supermarket
      - Gott i Gott
      - HELLOFRESH
      - ICA KVANTUM
      - GOTEBORGS ORIEN
      - GLADE JOHANS
      - LIDL
      - HEMKOP
      - eleven
      - CO 252 BACKAPLA
      - Hemköp
      - Saigon city
      - Indian groc
      - GARDSSALLSKAPET
      - INDIAN SUPERMARKET
      - Ica nara
      - Ica super
      - KONDITORI
      - Asian Liv
      - MINI STOP ASIAN FOOD
      - HISINGENS FISK
      - ARJEPLOGVILT

  Base:
    Pharmacy:
      - Apotek
      - apohem
      - Apotea
      - W*meds.com

    Dental:
      - frisktandv
      - AQUA DENTAL
      - Hisingen Tandvard
      - LINNEGATANS IMPLANTATK

    "[Hair cutting]":
      - Live Salong
      - Barbersh
      - DEELPO AB

    Makeup:
      - Kicks

    Doctor:
      - Barnmorskegruppen

    Gym:
      - Nordicwell

    "[Protein & supplements]":
      - GYMGROSSISTEN

    "[Contact lenses]":
      - misterspex

    CSN:
      - csn
    Akassa:
      - Akad.a-kassa
    Bank:
      - enkla vardag
      - ÅRSAVGIFT
    Phone:
      - hallon.se
      - hallon

  Home:
    Electricity:
      - gbg energi
      - göteborg energi
      - dinel

  Transport:
    "[Public Transportation]":
      - VASTTRAFIK
      - Västtrafik
    "[Parking home]":
      - Cyklisten parkerings
    "Parking":
      - Easypark
      - PARKSTER
      - PARKERING GÖTEB
    Gasoline:
      - OKQ8
      - INGO
      - ST1
    Fordonsskatt:
      - Fordonsskatt
    "[Car wash]":
      - GRIMBOS MEK
    "[Congestion tax]":
      - Trängselskat
    "[Infrastructure fee]":
      - Infrastrukt
    "[Car shop]":
      - HISINGE BIL
  Fun:
    "[Computer games]":
      - STEAMGAMES
      - Greenmangaming
    Cinema:
      - FILMSTADEN
    Streaming:
      - spotify
      - netflix.com
      - hbomax
      - audible
      - GOOGLE STORAGE
      - discovery+
      - HBO MAX
    Alcohol:
      - systembolaget
      - SCHNITZELPLATZ
      - ZAMENHOF
      - IRISH EMBASSY JERNTORG
      - Systembolage
      - Stena Alcohol

    Cafe:
      - Asti Italia
      - BROGYLLEN LANDALA
      - ESPRESSO HOUSE
      - Pressbyran
      - Hastevikskiosk
      - Jafaris Group
      - ME & TEA
      - MR CAKE

    "[Eating out]":
      - lilla istanbul
      - zosaki
      - sannegardens
      - restaurang istanbul
      - sushi tiden
      - DA BELLO ENOTECA
      - VIETNAMHAKET
      - TURKISK SULTAN
      - FOOD LAB
      - Kafe Alkemiste
      - INDISKA
      - COOP KONSUM
      - ZOZAKI JAPAN
      - BURGER KING
      - SUBWAY
      - FLYING BARELL
      - MEXIKANSKA MONARKIN
      - OLSTUGAN TULLEN
      - LILLA ISTANBUL
      - NADIAS RESTAURANG
      - Ramen-ya
      - Streetfood f
      - MOON THAI KITCHEN
      - Dubbel Gard
      - SYLOS
      - Lacsa pizzer
      - BACKAPLAN WOK
      - KG KELLARE
      - Osman s Grill
      - Morgon Coffee Roas
      - RESTAURANG CITY
      - MAX SKELLEFTEA
      - BAGERIET VEMDALEN
      - RESTAURANG TRIPTI
      - IDREGRILLEN
      - MCDONALDS
      - GLOBAL RESTAURANG
      - RESTAURANG MARIA
      - LUCKY SUSHI
      - INDIAN PALACE
      - FRASSES ARJEPLO
      - PIZZERIA
      - KANJANA BRANNSTROM THA
      - Cheers Pub
      - Foodora
      - JARNGRILLEN
      - SPIKAT
      - GOLDEN WAFFEL
      - Duy Tan
      - KFC GOTEBORG
      - Fiskebaren
      - Stena Mat
      - RESTAURANG BRS
      - NORDIC SPORTBAR
      - Bombay Bistro
      - Sukki-Ne
      - MAC S KEBAB OCH GATUKO

  Spending:
    Hornbach:
      - HORNBACH
    Zalando:
      - Zalando
    Stadium:
      - STADIUM
    Ahlens:
      - AHLENS
    Netonnet:
      - Netonnet
    "[H&M]":
      - HM SE0221
    Kjell:
      - KJELL
    Amazon:
      - AMAZONRETAIL
    "[Book store]":
      - AKADEMIBOKHANDE
    Blomsterlandet:
      - BLOMSTERLANDET
    "[Add Nature]":
      - addnature
    Airbnb:
      - AIRBNB
    XXL:
      - XXL
    STF:
      - STF RITSEM
    IKEA:
      - IKEA
    Puzzle:
      - pusselavenyn
    Swimming:
      - LUNDBYBADET
    Elgiganten:
      - Elgiganten
    Police:
      - POLISEN
    Klarna:
      - Klarna bank
    Books:
      - Klarna*bokus.com
    Bluebox:
      - Klarna*bluebox.se
    Biltema:
      - BILTEMA
    Flight:
      - KLM
      - PAL AIR DIGITAL
    Ekokul:
      - Ekokul
    Tickster:
      - TICKSTER
    "[Clas Ohlson]":
      - CLAS OHLSON
    "[Stena Cruise]":
      - Stena Line
    "Smartphoto":
      - smartphoto
    "[ÖoB]":
      - OOB BACKAPLAN
    "Brothers":
      - Brothers Nordstan
    "[SJ Train]":
      - SJ.SE
    "[Jack & Jones]":
      - K*bestseller
    Liseberg:
      - liseberg
    "[Wien Resa]":
      - CLASSIC ENSEMBLE VIENN
      - RYANAIR0000000FYF9TL0
    Museum:
      - SJÖFARTSMUSEET


ignored:
  - entercard group ab
  - lön
  - inbetalning bankgiro
  - Pension
  - skandia liv
  - 56990473967
  - folksam
  - Kåpan